Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	make_cfmid_energy_dash_collision_energy
	1
Select jobs to execute...

[Tue Jan 12 18:34:33 2021]
rule make_cfmid_energy_dash_collision_energy:
    input: /home/rictuar/coding_projects/fiehn_work/text_files/orthogonal_snakemake/[M-H]-/qtof/precursor_yes/collision_modified_[M-H]-_qtof_precursor_yes.txt
    output: /home/rictuar/coding_projects/fiehn_work/text_files/orthogonal_snakemake/[M-H]-/qtof/precursor_yes/cfmid-collision_[M-H]-_qtof_precursor_yes.txt
    jobid: 0
    wildcards: adduct=[M-H]-, instrument=qtof, precursor_status=precursor_yes

[Tue Jan 12 18:34:34 2021]
Error in rule make_cfmid_energy_dash_collision_energy:
    jobid: 0
    output: /home/rictuar/coding_projects/fiehn_work/text_files/orthogonal_snakemake/[M-H]-/qtof/precursor_yes/cfmid-collision_[M-H]-_qtof_precursor_yes.txt

RuleException:
CalledProcessError in line 80 of /home/rictuar/coding_projects/fiehn_work/small_scripts/orthogonal_snakemake/Snakefile:
Command 'set -euo pipefail;  /home/rictuar/anaconda3/bin/python3.8 /home/rictuar/coding_projects/fiehn_work/small_scripts/orthogonal_snakemake/.snakemake/scripts/tmpzoc0_yjp.make_cfmid_energy_dash_collision_energy.py' returned non-zero exit status 1.
  File "/home/rictuar/anaconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2317, in run_wrapper
  File "/home/rictuar/coding_projects/fiehn_work/small_scripts/orthogonal_snakemake/Snakefile", line 80, in __rule_make_cfmid_energy_dash_collision_energy
  File "/home/rictuar/anaconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 566, in _callback
  File "/home/rictuar/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/home/rictuar/anaconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 552, in cached_or_run
  File "/home/rictuar/anaconda3/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2348, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/rictuar/coding_projects/fiehn_work/small_scripts/orthogonal_snakemake/.snakemake/log/2021-01-12T183433.656269.snakemake.log
